- tests/test_routes.py
Made the following changes:
Added test_route_recommendation to ensure functionality of updating route.
> add test for updating route

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Made following changes:
1. Added endpoint for listing all recommendations.
2. Added tests for listing all recommendations.
3. Added tests for find_by_user and find_by_product
> Added List recommendation endpoint

- service/routes.py
- tests/factories.py
- tests/test_models.py
modified routes.py, factories.py, and test_models.py
> fiexed bugs, and modified root url to return useful information

- .github/workflows/ci.yml
Update CI workflow to fix build failures by configuring virtual environments, setting up Python cleanly, and pinning dependencies.
> Update CI workflow configuration

- .github/workflows/ci.yml
resolved dependency issue in ci.yml
> resolved dependency issue

- service/routes.py
- tests/test_routes.py
Adding back my previously deleted code with following changes:
-Added routes for find by productId
- Added test_routes for  find by productid
- Added routes for find by userId
- Added routes for find by usertId
> Merged my previous changes

- service/routes.py
- tests/test_routes.py
added test_routes for the following :
- Query by product_id
- Query by user_id
- Query by product_id and user_id
> added test_routes

- README_check.md
The CI badge showcasing if the code is CI is viable or not
> Add GitHub Actions CI badge to README

- service/routes.py
- tests/test_routes.py
Code is written for the routes which have to be edited as per the database model
> Add endpoint to retrieve and increment likes for recommendations

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
-Updated the Database model to include a new attribute num_likes
-Updated factory.py with num_likes
-Updated tests and routes to include num_likes
> Added num_likes to the DB model and updates tests

- .devcontainer/Dockerfile
- features/environment.py
- features/recommendations.feature
- features/steps/recommendations_steps.py
- features/steps/web_steps.py
- poetry.lock
- pyproject.toml
Added the following
-Updated the .devcontainer/Dockerfile
- Updated pyproject.toml file
- added features folder with .features file and steps for BDD
> bdd-final- added .features file

- service/routes.py
- tests/test_routes.py
> health route made

- service/static/index.html
> fixed index.html

- service/static/js/rest_api.js
- tests/test_routes.py
modified rest_api.js, test_routes.py.
> updated like action operation

- README.md
- service/routes.py
- tests/test_routes.py
This PR enhances the Recommendations API by:
1. Adding comprehensive query parameters to the List endpoint:
- Filter by score range (min_score, max_score)
- Filter by likes count (min_likes, max_likes)
- Filter by date range (from_date, to_date)
- Existing filters for user_id and product_id
2. Implementing a "Like" action endpoint:
- POST /recommendations/{id}/likes
- Increments the num_likes counter for a recommendation
- Returns updated recommendation object
The implementation includes full test coverage and follows REST API best practices for both query parameters and action endpoints.
Key files modified:
- service/routes.py (enhanced list endpoint and like action)
- tests/test_routes.py (new test cases)
- README.md (updated API documentation)
All tests passing with >95% coverage.
> Query list

- features/recommendations.feature
- features/steps/web_steps.py
- service/models.py
- service/routes.py
- service/static/js/rest_api.js
- tests/test_models.py
- tests/test_routes.py
There were some major issues with the code in the rest_api.js and also had to add new routes and functionality for the find and search.
> fixed all the bugs and made sure things work in all cases

- k8s/deployment.yaml
- k8s/postgresql.yaml
> fix env var name for k8s

- service/routes.py
- service/static/index.html
Updated the following for swagger implementation : 
- added undocumented response codes in routes.py
- updated index.html to for documentation link
> swagger-api-doc

- service/routes.py
Fixed the following things:
- Default datetime to current UTC time in payload 
- Documented 200 Response for num of likes endpoint
> fixed bugs

- .tekton/tasks.yaml
Correct parameter references in the script and enhance the task description for clarity.
> Fix parameter references and improve task description in tasks.yaml
